services:
  mysql-db:
    image: mysql
    restart: always
    platform: linux
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
#      - ./db_data:/var/lib/mysql
      - ./master_db/data:/var/lib/mysql
  nifi:
    image: apache/nifi:latest
    ports:
        - "8080:8080"
    environment:
      - NIFI_WEB_HTTP_PORT=8080
      - NIFI_WEB_HTTPS_PORT=8443
      - NIFI_LOGGING_LEVEL=INFO
    volumes:
      - ./nifi/data:/opt/nifi/nifi-current/data
      - ./nifi/conf:/opt/nifi/nifi-current/conf
    restart: unless-stopped
volumes:
  db_data:
  es-data:
    driver: local
  redis-data:

